version: "3.8"

services: # Backend Python com IA
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: removal-bg-backend
        restart: unless-stopped
        environment:
            - HOST=0.0.0.0
            - PORT=8000
            - WORKERS=2
            - LOG_LEVEL=info
            - SUPPRESS_PYTORCH_WARNINGS=true
            - CACHE_DIR=/app/cache
            - MAX_FILE_SIZE=2097152 # 2MB
            - MAX_BATCH_SIZE=5
            - MODEL_CACHE_SIZE=2
        volumes:
            - backend_cache:/app/cache
            - backend_logs:/app/logs
        ports:
            - "8000:8000"
        healthcheck:
            test:
                [
                    "CMD",
                    "python",
                    "-c",
                    "import requests; requests.get('http://localhost:8000/health', timeout=10)",
                ]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 60s        deploy:
            resources:
                limits:
                    memory: 4G
                reservations:
                    memory: 2G
        networks:
            - removal-bg-network

    # Nginx Reverse Proxy
    nginx:
        image: nginx:alpine
        container_name: removal-bg-nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/conf.d:/etc/nginx/conf.d:ro
            - nginx_logs:/var/log/nginx
            - ./ssl:/etc/nginx/ssl:ro
        depends_on:
            - backend
        networks:
            - removal-bg-network

    # Redis para Cache (opcional, para futuras otimizações)
    redis:
        image: redis:7-alpine
        container_name: removal-bg-redis
        restart: unless-stopped
        command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
        volumes:
            - redis_data:/data
        ports:
            - "6379:6379"
        networks:
            - removal-bg-network

volumes:
    backend_cache:
        driver: local
    backend_logs:
        driver: local
    redis_data:
        driver: local
    nginx_logs:
        driver: local

networks:
    removal-bg-network:
        driver: bridge
