version: "3.8"

services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: tira-fundo-backend
        ports:
            - "8000:8000"
        environment:
            - HOST=0.0.0.0
            - PORT=8000
        env_file:
            - .env
        volumes:
            - ./uploads:/app/uploads # Para arquivos temporários se necessário
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
